Document: nginx
Title: Debian nginx Manual
Author: <insert document author here>
Abstract: This manual describes what nginx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nginx/nginx.sgml.gz

Format: postscript
Files: /usr/share/doc/nginx/nginx.ps.gz

Format: text
Files: /usr/share/doc/nginx/nginx.text.gz

Format: HTML
Index: /usr/share/doc/nginx/html/index.html
Files: /usr/share/doc/nginx/html/*.html
