name: Hello world

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run ls
      run: ls ./
    - name: Run pwd
      run: pwd
    - name: check distribution
      run: cat /etc/lsb-release
